name = "made-website"
compatibility_date = "2023-12-01"

[env.production]
compatibility_date = "2023-12-01"

# Cloudflare Pages configuration
pages_build_output_dir = "_site"

# Environment variables (optional - can be set in Cloudflare dashboard)
# [env.production.vars]
# JEKYLL_ENV = "production"